// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/kctjohnson/mid-blog/internal/templates/utils"
import "github.com/kctjohnson/mid-blog/internal/templates/components"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"grid grid-cols-2 bg-yellow-500 pl-5 pr-5\" style=\"border-bottom: 1px solid black\"><div class=\"col-span-2 flex justify-between p-2 items-center\" style=\"border-bottom: 1px solid black\"><div><h1 class=\"text-2xl font-bold ml-1\">Mid</h1></div><div class=\"mr-1\"><a href=\"/\" class=\"p-1 text-sm\">Our Story</a> <a href=\"/\" class=\"p-1 text-sm\">Membership</a> <a href=\"/\" class=\"p-1 text-sm\">Write</a> <a href=\"/\" class=\"p-1 text-sm\">Sign In</a></div></div><div class=\"flex justify-center items-center\"><div class=\"grid grid-rows-4\"><h1 class=\"text-4xl font-bold text-center\">Stay Mediocre, Go Somewhere</h1><p class=\"text-2xl\">Find AI generated blog posts on any topic.</p><div class=\"row-span-2 self-end\"><button class=\"btn rounded-full bg-black border-black text-white hover:bg-gray-800 mt-4\">Start Reading</button></div></div></div><p class=\"p-8 text-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(utils.WordGenerator.Sentences(6))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/index.templ`, Line: 28, Col: 64}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div><div class=\"pt-8 pb-4 px-40\"><div class=\"flex flex-row items-center pb-4\"><svg width=\"28\" height=\"29\" viewBox=\"0 0 28 29\" fill=\"none\" class=\"ji ah\"><path fill=\"#fff\" d=\"M0 .8h28v28H0z\"></path> <g opacity=\"0.8\" clip-path=\"url(#trending_svg__clip0)\"><path fill=\"#fff\" d=\"M4 4.8h20v20H4z\"></path> <circle cx=\"14\" cy=\"14.79\" r=\"9.5\" stroke=\"#000\"></circle> <path d=\"M5.46 18.36l4.47-4.48M9.97 13.87l3.67 3.66M13.67 17.53l5.1-5.09M16.62 11.6h3M19.62 11.6v3\" stroke=\"#000\" stroke-linecap=\"round\"></path></g> <defs><clipPath id=\"trending_svg__clip0\"><path fill=\"#fff\" transform=\"translate(4 4.8)\" d=\"M0 0h20v20H0z\"></path></clipPath></defs></svg><p class=\"text-sm font-semibold\">Trending on Mid</p></div><div class=\"grid grid-cols-3 gap-5 justify-items-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = utils.SkeletonPostCard().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = utils.SkeletonPostCard().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = utils.SkeletonPostCard().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = utils.SkeletonPostCard().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = utils.SkeletonPostCard().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = utils.SkeletonPostCard().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = components.Layout("MidBlog").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
